# Generated by Django 3.2 on 2021-04-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('goal_id', models.IntegerField(db_column='Goal_ID', primary_key=True, serialize=False)),
                ('goal_name', models.CharField(blank=True, db_column='Goal_name', max_length=40, null=True)),
                ('goal_target', models.TextField(blank=True, db_column='Goal_target', null=True)),
                ('goal_current', models.TextField(blank=True, db_column='Goal_current', null=True)),
            ],
            options={
                'db_table': 'Goals',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('transaction_id', models.IntegerField(db_column='transaction_ID', primary_key=True, serialize=False)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('transaction_amt', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Transactions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.IntegerField(db_column='user_ID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, max_length=40, null=True)),
                ('user_password', models.CharField(blank=True, max_length=40, null=True)),
                ('user_email', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
